import { completeDevice, loadDeviceState, requestDevice, saveDeviceState, validateDeviceProtection } from './device';
import { decryptPrivateBundle, digestAuthorizationToken, encryptPrivateBundle, fingerprintPublicJwk, generateAuthorizationToken, generateWrappingKeyPair } from './device-crypto';
import { verifyDeviceLease } from './lease';
import { supabase } from './supabase';
import { arrayBufferToBase64, base64ToArrayBuffer } from './crypto';
import type { DeviceLease, DeviceLocalState, EnvelopeCiphertext, PrivateDeviceBundle, RecoveryKdf } from '../types';

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const B64URL = /^[A-Za-z0-9_-]+$/;
const B64 = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/;
const fail = (message = 'Invalid device security response.'): never => { throw new Error(message); };
const object = (value: unknown, message = 'Invalid device security response.'): Record<string, unknown> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : fail(message);
const exact = (value: unknown, fields: string[], message = 'Invalid device security response.'): Record<string, unknown> => { const data = object(value, message); if (Object.keys(data).length !== fields.length || !fields.every(field => Object.prototype.hasOwnProperty.call(data, field))) fail(message); return data; };
const uuid = (value: unknown, message = 'Invalid device security response.'): string => typeof value === 'string' && UUID.test(value) ? value : fail(message);
const b64url = (bytes: Uint8Array): string => arrayBufferToBase64(bytes).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
const b64urlBytes = (value: unknown, min: number, max = min): Uint8Array => {
    if (typeof value !== 'string' || !B64URL.test(value) || value.length % 4 === 1) fail();
    const encoded = value as string; const bytes = new Uint8Array(base64ToArrayBuffer(`${encoded.replace(/-/g, '+').replace(/_/g, '/')}${'==='.slice((encoded.length + 3) % 4)}`));
    if (bytes.byteLength < min || bytes.byteLength > max || b64url(bytes) !== encoded) fail(); return bytes;
};
const b64urlString = (value: unknown, min: number, max = min): string => { const bytes = b64urlBytes(value, min, max); try { return value as string; } finally { bytes.fill(0); } };
const b64 = (value: unknown, min: number, max = min): string => { if (typeof value !== 'string' || !B64.test(value)) fail(); const encoded = value as string; const bytes = new Uint8Array(base64ToArrayBuffer(encoded)); if (bytes.byteLength < min || bytes.byteLength > max || arrayBufferToBase64(bytes) !== encoded) fail(); return encoded; };
const envelope = (value: unknown): EnvelopeCiphertext => { const data = exact(value, ['version', 'iv', 'data']); if (data.version !== 2) fail(); return { version: 2, iv: b64(data.iv, 12), data: b64(data.data, 16, Number.MAX_SAFE_INTEGER) }; };
const generation = (value: unknown): string => uuid(value);
const protection = (value: unknown): Record<string, unknown> => validateDeviceProtection(value, 'passkey-prf');
const edge = async (body: Record<string, unknown>): Promise<unknown> => {
    const { data, error } = await supabase.functions.invoke('vault-security', { body });
    if (!error) return data;
    // The function answers with a short non-secret code; surface it so failures are diagnosable.
    const response = (error as { context?: unknown }).context;
    const code = response instanceof Response ? await response.clone().json().then(value => typeof value?.error === 'string' ? value.error : typeof value?.code === 'string' ? value.code : `HTTP ${response.status}`, () => `HTTP ${response.status}`) : error.name;
    fail(`Device security request failed (${code}).`);
};
const rpc = async (name: string, args: Record<string, unknown>): Promise<unknown> => { const { data, error } = await supabase.rpc(name, args); if (error) fail('Device security request failed.'); return data; };

export interface PasskeyProtection { version: 1; rpId: 'quotes.darkmg1.dev'; credentialId: string; prfSalt: string; kdf: 'HKDF-SHA-256' }
export interface PasskeyRestoreDevice { deviceId: string; generation: string; protection: PasskeyProtection; publicKeyFingerprint: string; encryptedPrivateBundle: EnvelopeCiphertext }

export async function getPasskeyRestoreDevices(): Promise<PasskeyRestoreDevice[]> {
    const response = exact(await rpc('get_passkey_restore_devices', {}), ['generation', 'devices'], 'Invalid passkey restore response.');
    generation(response.generation);
    if (!Array.isArray(response.devices)) fail('Invalid passkey restore response.');
    return (response.devices as unknown[]).map(value => { const data = exact(value, ['device_id', 'protection_mode', 'protection', 'public_key_fingerprint', 'encrypted_private_bundle', 'generation'], 'Invalid passkey restore response.'); if (data.protection_mode !== 'passkey-prf') fail('Invalid passkey restore response.'); b64urlBytes(data.public_key_fingerprint, 32); return { deviceId: uuid(data.device_id, 'Invalid passkey restore response.'), generation: generation(data.generation), protection: protection(data.protection) as unknown as PasskeyProtection, publicKeyFingerprint: data.public_key_fingerprint as string, encryptedPrivateBundle: envelope(data.encrypted_private_bundle) }; });
}

const lease = (value: unknown): DeviceLease => { const data = exact(value, ['version', 'claims', 'signature'], 'Invalid device lease.'); if (data.version !== 1 || !Array.isArray(data.claims) || data.claims.length !== 7 || typeof data.signature !== 'string') fail('Invalid device lease.'); b64(data.signature, 1, Number.MAX_SAFE_INTEGER); return { version: 1, claims: data.claims as DeviceLease['claims'], signature: data.signature as string }; };
export async function renewDeviceLease(input: { accountId: string; deviceId: string; token: string; generation: string; publicKeyFingerprint: string; now?: number }): Promise<DeviceLocalState> {
    const state = await loadDeviceState(input.accountId); if (!state || state.deviceId !== input.deviceId) fail('Device enrollment state is missing.'); const current = state as DeviceLocalState;
    b64urlBytes(input.token, 32); b64urlBytes(input.publicKeyFingerprint, 32); const signed = lease(await edge({ action: 'renew', deviceId: input.deviceId, token: input.token }));
    if (!await verifyDeviceLease(signed, { now: input.now ?? Date.now(), deviceId: input.deviceId, accountId: input.accountId, generation: input.generation, publicKeyFingerprint: input.publicKeyFingerprint })) fail('Invalid device lease.');
    const next: DeviceLocalState = { ...current, lease: signed }; await saveDeviceState(next); return next;
}

/** A completion response keeps only a lease already verified and saved locally. */
export async function renewThenCompleteDevice(input: { accountId: string; deviceId: string; token: string; generation: string; leaseGeneration?: string; publicKeyFingerprint: string; rememberedKey?: CryptoKey }): Promise<DeviceLocalState> {
    await renewDeviceLease({ ...input, generation: input.leaseGeneration ?? input.generation });
    return completeDevice(input.accountId, input.deviceId, input.token, input.rememberedKey, input.generation);
}

type PrfCredential = { rawId: ArrayBuffer; getClientExtensionResults(): { prf?: { enabled?: boolean; results?: { first?: ArrayBuffer } } } };
const passkeyError = (error: unknown): never => { if ((error as { name?: unknown })?.name === 'NotAllowedError') throw new Error('Passkey request was cancelled. Use another device, recovery, or an administrator.'); throw new Error('Passkey is unavailable. Use another device, recovery, or an administrator.'); };
export async function unlockPasskey(input: PasskeyProtection, serverChallenge?: string): Promise<CryptoKey> {
    const checked = protection(input) as unknown as PasskeyProtection; const credentialId = b64urlBytes(checked.credentialId, 1, 1023); const salt = b64urlBytes(checked.prfSalt, 32); let challenge: Uint8Array | undefined;
    try { challenge = serverChallenge === undefined ? crypto.getRandomValues(new Uint8Array(32)) : b64urlBytes(serverChallenge, 32); const credentials = (typeof navigator === 'undefined' ? undefined : navigator.credentials) as CredentialsContainer | undefined; if (!credentials) fail('Passkey is unavailable. Use another device, recovery, or an administrator.'); const credential = await (credentials as CredentialsContainer).get({ publicKey: { challenge, rpId: checked.rpId, allowCredentials: [{ type: 'public-key', id: credentialId }], userVerification: 'required', extensions: { prf: { eval: { first: salt } } } } } as CredentialRequestOptions) as unknown as PrfCredential | null; const result = credential?.getClientExtensionResults().prf?.results?.first; if (!result || result.byteLength !== 32) fail('Passkey does not support PRF. Use another device, recovery, or an administrator.'); const prf = new Uint8Array(result as ArrayBuffer); try { const material = await crypto.subtle.importKey('raw', prf, 'HKDF', false, ['deriveKey']); return crypto.subtle.deriveKey({ name: 'HKDF', hash: 'SHA-256', salt: new Uint8Array(), info: new TextEncoder().encode('quotevault/passkey-bundle/v1') }, material, { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']); } finally { prf.fill(0); } } catch (error) { if (error instanceof Error && error.message.startsWith('Passkey')) throw error; return passkeyError(error); } finally { credentialId.fill(0); salt.fill(0); challenge?.fill(0); }
}

export async function webauthnChallenge(purpose: 'registration' | 'restoration'): Promise<string> { const data = exact(await edge({ action: 'webauthn_challenge', purpose }), ['purpose', 'challenge'], 'Invalid passkey challenge.'); if (data.purpose !== purpose) fail('Invalid passkey challenge.'); return b64urlString(data.challenge, 32); }
export async function registerPasskey(input: { userId: string; userName: string; displayName: string }): Promise<PasskeyProtection & { key: CryptoKey }> {
    uuid(input.userId, 'Invalid passkey registration.'); if (!input.userName || !input.displayName) fail('Invalid passkey registration.'); const salt = crypto.getRandomValues(new Uint8Array(32));
    try { const credentials = typeof navigator === 'undefined' ? undefined : navigator.credentials; if (!credentials) fail('Passkey is unavailable. Use another device, recovery, or an administrator.'); const created = await (credentials as CredentialsContainer).create({ publicKey: { challenge: b64urlBytes(await webauthnChallenge('registration'), 32), rp: { id: 'quotes.darkmg1.dev', name: 'QuoteVault' }, user: { id: new TextEncoder().encode(input.userId), name: input.userName, displayName: input.displayName }, pubKeyCredParams: [{ type: 'public-key', alg: -7 }], authenticatorSelection: { userVerification: 'required' }, attestation: 'none', extensions: { prf: { eval: { first: salt } } } } } as CredentialCreationOptions) as unknown as PrfCredential | null; const enabled = created?.getClientExtensionResults().prf?.enabled; const rawId = created?.rawId as unknown as { byteLength?: unknown }; if (!created || !enabled || typeof rawId?.byteLength !== 'number') fail('Passkey does not support PRF. Use another device, recovery, or an administrator.'); const credential = created as PrfCredential; const protectionValue: PasskeyProtection = { version: 1, rpId: 'quotes.darkmg1.dev', credentialId: b64url(new Uint8Array(credential.rawId)), prfSalt: b64url(salt), kdf: 'HKDF-SHA-256' }; return { ...protectionValue, key: await unlockPasskey(protectionValue, await webauthnChallenge('registration')) }; } catch (error) { if (error instanceof Error && error.message.startsWith('Passkey')) throw error; return passkeyError(error); } finally { salt.fill(0); }
}

const recoveryKdf = (value: unknown): RecoveryKdf => { const data = exact(value, ['version', 'salt', 'iterations'], 'Invalid recovery response.'); if (data.version !== 1 || data.iterations !== 600000) fail('Invalid recovery response.'); return { version: 1, salt: b64(data.salt, 16, 64), iterations: 600000 }; };
export interface RecoveryBegin { challengeId: string; recoveryKeyId: string; publicKeyFingerprint: string; ciphertext: string; encryptedPrivateKey: EnvelopeCiphertext; kdf: RecoveryKdf }
export async function beginRecovery(): Promise<RecoveryBegin> { const data = exact(await edge({ action: 'begin_recovery' }), ['challengeId', 'recoveryKeyId', 'publicKeyFingerprint', 'ciphertext', 'encryptedPrivateKey', 'kdf'], 'Invalid recovery response.'); return { challengeId: uuid(data.challengeId, 'Invalid recovery response.'), recoveryKeyId: uuid(data.recoveryKeyId, 'Invalid recovery response.'), publicKeyFingerprint: b64urlString(data.publicKeyFingerprint, 32, 32), ciphertext: b64urlString(data.ciphertext, 384, 384), encryptedPrivateKey: envelope(data.encryptedPrivateKey), kdf: recoveryKdf(data.kdf) }; }
export async function completeRecovery(input: { challengeId: string; recoveryKeyId: string; response: string }): Promise<{ recoveryKeyId: string; generation: string; wrappedKey: string; transitionToken: string }> { const expectedRecoveryKeyId = uuid(input.recoveryKeyId, 'Invalid recovery response.'); const data = exact(await rpc('complete_recovery', { p_challenge_id: uuid(input.challengeId, 'Invalid recovery response.'), p_response: b64urlString(input.response, 32, 32) }), ['recovery_key_id', 'generation', 'wrapped_key', 'transition_token'], 'Invalid recovery response.'); const recoveryKeyId = uuid(data.recovery_key_id, 'Invalid recovery response.'); if (recoveryKeyId !== expectedRecoveryKeyId) fail('Invalid recovery response.'); return { recoveryKeyId, generation: generation(data.generation), wrappedKey: b64urlString(data.wrapped_key, 384, 384), transitionToken: b64urlString(data.transition_token, 32, 32) }; }
export async function activateRecoveredDevice(input: { challengeId: string; transitionToken: string; requestId: string; enrollmentFingerprint: string; generation: string; wrappedKey: string }): Promise<{ deviceId: string; generation: string }> { const data = exact(await rpc('activate_recovered_device', { p_challenge_id: uuid(input.challengeId, 'Invalid recovery response.'), p_transition_token: b64urlString(input.transitionToken, 32, 32), p_request_id: uuid(input.requestId, 'Invalid recovery response.'), p_enrollment_fingerprint: b64urlString(input.enrollmentFingerprint, 32, 32), p_generation: generation(input.generation), p_wrapped_key: b64urlString(input.wrappedKey, 384, 384) }), ['device_id', 'generation'], 'Invalid recovery response.'); const deviceId = uuid(data.device_id, 'Invalid recovery response.'); const currentGeneration = generation(data.generation); if (deviceId !== input.requestId || currentGeneration !== input.generation) fail('Invalid recovery response.'); return { deviceId, generation: currentGeneration }; }
export async function createRecoveryKey(input: { recoveryKeyId: string; publicJwk: JsonWebKey; publicKeyFingerprint: string; encryptedPrivateKey: EnvelopeCiphertext; kdf: RecoveryKdf; generation: string; wrappedKey: string; deviceId: string; token: string }, replace = false): Promise<{ recoveryKeyId: string; generation: string }> { const recoveryKeyId = uuid(input.recoveryKeyId, 'Invalid recovery response.'); const currentGeneration = generation(input.generation); if (await fingerprintPublicJwk(input.publicJwk) !== b64urlString(input.publicKeyFingerprint, 32, 32)) fail('Invalid recovery response.'); const data = exact(await rpc(replace ? 'replace_recovery_key' : 'create_recovery_key', { p_recovery_key_id: recoveryKeyId, p_public_jwk: input.publicJwk, p_public_key_fingerprint: input.publicKeyFingerprint, p_encrypted_private_key: envelope(input.encryptedPrivateKey), p_kdf: recoveryKdf(input.kdf), p_generation: currentGeneration, p_wrapped_key: b64urlString(input.wrappedKey, 384, 384), p_device_id: uuid(input.deviceId, 'Invalid recovery response.'), p_token: b64urlString(input.token, 32, 32) }), ['recovery_key_id', 'generation'], 'Invalid recovery response.'); const responseKeyId = uuid(data.recovery_key_id, 'Invalid recovery response.'); const responseGeneration = generation(data.generation); if (responseKeyId !== recoveryKeyId || responseGeneration !== currentGeneration) fail('Invalid recovery response.'); return { recoveryKeyId: responseKeyId, generation: responseGeneration }; }
export const replaceRecoveryKey = (input: Parameters<typeof createRecoveryKey>[0]) => createRecoveryKey(input, true);

export async function prepareDeviceEnrollment(input: { accountId: string; label: string; requestKind: 'first' | 'additional' | 'recovery'; protectionMode: 'remembered' | 'passkey-prf'; protection: Record<string, unknown>; encryptionKey?: CryptoKey }): Promise<{ deviceId: string; requestId: string; enrollmentFingerprint: string; authorizationToken: string; privateKey: CryptoKey; publicKeyFingerprint: string; rememberedKey?: CryptoKey }> {
    const deviceId = crypto.randomUUID(); uuid(input.accountId); const checked = input.protectionMode === 'remembered' ? validateDeviceProtection(input.protection, 'remembered') : protection(input.protection); const key = input.protectionMode === 'remembered' ? await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']) : input.encryptionKey; if (!key) fail('Passkey key is required.');
    const encryptionKey = key as CryptoKey; const pair = await generateWrappingKeyPair(); const publicJwk = await crypto.subtle.exportKey('jwk', pair.publicKey); const privateJwk = await crypto.subtle.exportKey('jwk', pair.privateKey); const publicKeyFingerprint = await fingerprintPublicJwk(publicJwk); const authorizationToken = generateAuthorizationToken(); const tokenDigest = await digestAuthorizationToken(authorizationToken); const encryptedPrivateBundle = await encryptPrivateBundle({ version: 1, privateJwk, authorizationToken }, encryptionKey, { accountId: input.accountId, recordId: deviceId, publicKeyFingerprint, protectionMode: input.protectionMode, version: 1, ...(input.protectionMode === 'passkey-prf' ? { protection: checked as unknown as PasskeyProtection } : {}) }); const state: DeviceLocalState = { accountId: input.accountId, deviceId, publicKeyFingerprint, protectionMode: input.protectionMode, protection: checked, encryptedPrivateBundle }; if (input.protectionMode === 'remembered') state.rememberedKey = encryptionKey; await saveDeviceState(state); const request = await requestDevice({ deviceId, ownerId: input.accountId, label: input.label, publicJwk, publicKeyFingerprint, tokenDigest, protectionMode: input.protectionMode, protection: checked, encryptedPrivateBundle, requestKind: input.requestKind }); return { deviceId, requestId: request.requestId, enrollmentFingerprint: request.enrollmentFingerprint, authorizationToken, privateKey: pair.privateKey, publicKeyFingerprint, ...(input.protectionMode === 'remembered' ? { rememberedKey: encryptionKey } : {}) };
}

export async function decryptDeviceBundle(state: DeviceLocalState, key: CryptoKey): Promise<{ privateKey: CryptoKey; authorizationToken: string }> { const bundle: PrivateDeviceBundle = await decryptPrivateBundle(state.encryptedPrivateBundle, key, { accountId: state.accountId, recordId: state.deviceId, publicKeyFingerprint: state.publicKeyFingerprint, protectionMode: state.protectionMode, version: 1, ...(state.protectionMode === 'passkey-prf' ? { protection: validateDeviceProtection(state.protection, 'passkey-prf') as unknown as PasskeyProtection } : {}) }); const privateKey = await crypto.subtle.importKey('jwk', bundle.privateJwk, { name: 'RSA-OAEP', hash: 'SHA-256' }, false, ['decrypt']); return { privateKey, authorizationToken: bundle.authorizationToken }; }
