import { useEffect, useState } from 'react';
import QRCode from 'qrcode';
import { Plus, RefreshCw, ShieldAlert, Trash2 } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { isAdminUser, ADMIN_EMAIL } from '../lib/access';
import { formatEnrollmentCode, getDeviceRequest, type DeviceRequest } from '../lib/device';
import { useAuth } from '../hooks/useAuth';
import { useCrypto } from '../hooks/useCrypto';
import { getErrorMessage } from './ui';

export function ApprovalRequest({ requestId, fingerprint }: { requestId: string; fingerprint: string }) {
    const { approveDeviceRequest } = useCrypto();
    const [request, setRequest] = useState<DeviceRequest | null>(null), [code, setCode] = useState(''), [expectedCode, setExpectedCode] = useState(''), [qr, setQr] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
    useEffect(() => { let live = true; void (async () => { try { const next = await getDeviceRequest(requestId); if (next.enrollmentFingerprint !== fingerprint) throw new Error('This approval link does not match the pending device request.'); const nextCode = await formatEnrollmentCode(next.enrollmentFingerprint); const url = `https://quotes.darkmg1.dev/#approve?request=${requestId}&fingerprint=${encodeURIComponent(next.enrollmentFingerprint)}`; const image = await QRCode.toDataURL(url, { margin: 1, width: 240 }); if (live) { setRequest(next); setExpectedCode(nextCode); setQr(image); } } catch (cause) { if (live) setError(cause instanceof Error ? cause.message : 'Could not load the device request.'); } })(); return () => { live = false; }; }, [fingerprint, requestId]);
    const approve = async () => { if (!request) return; setBusy(true); setError(''); try { await approveDeviceRequest(requestId, fingerprint, code); setError('Device approved. The requesting device can now unlock.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not approve this device.'); } finally { setBusy(false); } };
    return <div className="px-4 py-8 space-y-5"><h2 className="text-2xl font-bold text-white">Approve device</h2>{error && <p role="alert" className="text-sm text-red-300">{error}</p>}{request && <><p className="text-slate-300">{request.label} · {request.protectionMode === 'passkey-prf' ? 'Passkey PRF' : 'Remembered browser'}</p><p className="text-sm text-slate-400">Compare this code with the requesting device before approving.</p><p className="font-mono text-2xl tracking-widest text-white">{expectedCode}</p>{qr && <img src={qr} alt="Requesting device approval QR code" className="bg-white p-2 rounded-xl" />}<label className="block text-sm text-slate-300">Verification code<input aria-label="Verification code" value={code} onChange={event => setCode(event.target.value)} autoComplete="off" className="mt-1 w-full rounded-xl bg-slate-900 border border-slate-700 p-3 text-white" /></label><button type="button" disabled={busy || code.trim().toUpperCase() !== expectedCode} onClick={() => void approve()} className="w-full bg-primary-600 disabled:opacity-50 py-3 rounded-xl">{busy ? 'Approving…' : 'Approve device'}</button></>}</div>;
}

export const AdminDashboard = () => {
    const { user } = useAuth(); const { deviceId, getDeviceAuthorization } = useCrypto(); const isAdmin = isAdminUser(user); const [allowlist, setAllowlist] = useState<{ id: string; email: string }[]>([]); const [email, setEmail] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
    const authorization = async () => deviceId ? await getDeviceAuthorization() : null;
    const refresh = async () => { setBusy(true); setError(''); try { const auth = await authorization(); const { data, error } = await supabase.rpc('list_members', { p_device_id: auth?.deviceId ?? null, p_device_token: auth?.token ?? null }); if (error) throw error; if (data === null || !Array.isArray(data)) throw new Error('Device authorization was denied. Unlock this device and retry.'); setAllowlist(data.filter((item): item is { id: string; email: string } => !!item && typeof item === 'object' && typeof item.id === 'string' && typeof item.email === 'string')); } catch (cause) { setError(getErrorMessage(cause, 'Could not load allowed emails.')); } finally { setBusy(false); } };
    // eslint-disable-next-line react-hooks/set-state-in-effect
    useEffect(() => { if (isAdmin) void refresh(); }, [isAdmin]);
    const add = async (event: React.FormEvent) => { event.preventDefault(); if (!email.trim()) return; setBusy(true); setError(''); try { const auth = await authorization(); const { data, error } = await supabase.rpc('add_member', { p_email: email.trim().toLowerCase(), p_device_id: auth?.deviceId ?? null, p_device_token: auth?.token ?? null }); if (error) throw error; if (data === null || typeof data !== 'object' || typeof data.email !== 'string') throw new Error('Device authorization was denied. Unlock this device and retry.'); setEmail(''); await refresh(); } catch (cause) { setError(getErrorMessage(cause, 'Could not add email.')); } finally { setBusy(false); } };
    const remove = async (item: { id: string; email: string }) => { setBusy(true); setError(''); try { const auth = await authorization(); const { data, error } = await supabase.rpc('remove_member_access', { p_member_id: item.id, p_device_id: auth?.deviceId ?? null, p_device_token: auth?.token ?? null }); if (error) throw error; if (data === null || typeof data !== 'object' || data.status !== 'removed' || typeof data.id !== 'string') throw new Error('Device authorization was denied. Unlock this device and retry.'); const ownerId = data.owner_id; if (ownerId !== null && typeof ownerId !== 'string') throw new Error('Access was removed, but the owner session could not be identified.'); if (ownerId) { const invalidation = await supabase.functions.invoke('vault-security', { body: { action: 'invalidate_member_session', ownerId } }); if (invalidation.error || !invalidation.data || invalidation.data.ownerId !== ownerId || invalidation.data.status !== 'invalidated') { setError('Member access was removed, but their active session could not be invalidated.'); await refresh(); return; } } await refresh(); } catch (cause) { setError(getErrorMessage(cause, 'Could not remove email.')); } finally { setBusy(false); } };
    if (!isAdmin) return <div className="p-8 text-center"><ShieldAlert className="w-12 h-12 text-red-400 mx-auto" /><h2 className="mt-4 text-2xl font-bold">Access denied</h2></div>;
    return <div className="px-4 py-6 space-y-6"><div className="flex justify-between"><div><h2 className="text-2xl font-bold text-white">Access control</h2><p className="text-sm text-slate-400">Manage allowed sign-up emails and approve devices from their secure link.</p></div><button aria-label="Refresh allowlist" onClick={() => void refresh()}><RefreshCw className={busy ? 'animate-spin' : ''} /></button></div>{error && <p role="alert" className="text-red-300">{error}</p>}<form onSubmit={add} className="flex gap-2"><input aria-label="Email address to allow" type="email" required value={email} onChange={event => setEmail(event.target.value)} className="flex-1 rounded-xl bg-slate-900 border border-slate-700 p-3 text-white" /><button aria-label="Add email to allowlist" disabled={busy} className="rounded-xl bg-primary-600 px-5"><Plus /></button></form><ul className="divide-y divide-slate-700">{allowlist.map(item => <li key={item.id} className="py-3 flex justify-between"><span>{item.email}</span><button aria-label={`Remove ${item.email} from allowlist`} disabled={busy || item.email.trim().toLowerCase() === ADMIN_EMAIL} onClick={() => void remove(item)}><Trash2 className="w-4 h-4 text-red-400" /></button></li>)}</ul></div>;
};
