import { useEffect, useState } from 'react';
import { Loader2, RefreshCw, Trash2 } from 'lucide-react';
import { listOwnDevices, revokeOwnDevice, type DeviceSummary } from '../lib/device';
import { useCrypto } from '../hooks/useCrypto';
import { confirmRecoveryPhrase, generateRecoveryPhrase, recoveryConfirmationPositions } from '../lib/recovery-phrase';

const time = (value: string | null) => value ? new Date(value).toLocaleString() : 'Never';

export function DeviceSecurity() {
    const { deviceId, getDeviceAuthorization, forgetDevice, setupRecovery, enrollDevice, checkDeviceApproval, preparedGeneration } = useCrypto();
    const [devices, setDevices] = useState<DeviceSummary[]>([]); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [phrase, setPhrase] = useState<string[] | null>(null); const [positions, setPositions] = useState<number[]>([]); const [answers, setAnswers] = useState(['', '', '']); const [replace, setReplace] = useState(false);
    const refresh = async () => { setBusy('refresh'); setError(''); try { setDevices(await listOwnDevices()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load devices.'); } finally { setBusy(''); } };
    // eslint-disable-next-line react-hooks/set-state-in-effect
    useEffect(() => { void refresh(); }, []);
    const revoke = async (id: string) => { setBusy(id); setError(''); try { const auth = await getDeviceAuthorization(); await revokeOwnDevice(id, auth.token); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not revoke device.'); } finally { setBusy(''); } };
    const forget = async () => { setBusy('forget'); setError(''); try { await forgetDevice(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not forget this device.'); } finally { setBusy(''); } };
    const startRecovery = () => { setPhrase(generateRecoveryPhrase()); setPositions(recoveryConfirmationPositions()); setAnswers(['', '', '']); setReplace(false); };
    const saveRecovery = async () => { if (!phrase || !confirmRecoveryPhrase(phrase, answers, positions)) { setError('Enter the requested recovery words exactly.'); return; } setBusy('recovery'); setError(''); try { await setupRecovery(phrase.join(' '), replace); setPhrase(null); setPositions([]); setAnswers(['', '', '']); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save recovery phrase.'); } finally { setBusy(''); } };
    const enroll = async (mode: 'remembered' | 'passkey-prf') => { setBusy(mode); setError(''); try { await enrollDevice(mode); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not request this device.'); } finally { setBusy(''); } };
    return <section className="bg-surface/80 border border-slate-700/50 rounded-3xl p-6 sm:p-8 space-y-4">
        <div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold text-white">Devices</h3><p className="text-sm text-slate-400">Approved devices can decrypt this vault while their lease is valid.</p></div><button type="button" aria-label="Refresh devices" onClick={() => void refresh()} disabled={!!busy} className="p-2 text-slate-300"><RefreshCw className={busy === 'refresh' ? 'animate-spin w-5 h-5' : 'w-5 h-5'} /></button></div>
        {error && <p role="alert" className="text-sm text-red-400">{error}</p>}
        <ul className="divide-y divide-slate-700/50">{devices.map(device => <li key={device.id} className="py-4 flex gap-3 justify-between"><div><p className="text-white font-medium">{device.label}{device.id === deviceId ? ' (this device)' : ''}</p><p className="text-xs text-slate-400">{device.protection_mode === 'passkey-prf' ? 'Passkey PRF' : 'Remembered browser'} · {device.status}</p><p className="text-xs text-slate-500">Last sync: {time(device.last_sync_at)} · Lease: {time(device.lease_expires_at)}</p></div>{device.status === 'active' && device.id !== deviceId && <button type="button" onClick={() => void revoke(device.id)} disabled={!!busy} className="text-sm text-red-400">{busy === device.id ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Revoke'}</button>}</li>)}</ul>
        {preparedGeneration && <div className="border-t border-slate-700 pt-4 space-y-2"><h4 className="font-medium text-white">Prepared vault device</h4><p className="text-xs text-slate-400">Request approval for this browser, then unlock it here to recover the prepared vault key.</p><button type="button" onClick={() => void enroll('remembered')} disabled={!!busy} className="w-full border border-slate-600 py-2 rounded-xl">{busy === 'remembered' ? 'Requesting…' : 'Remember this device'}</button><button type="button" onClick={() => void enroll('passkey-prf')} disabled={!!busy} className="w-full border border-slate-600 py-2 rounded-xl">{busy === 'passkey-prf' ? 'Requesting…' : 'Set up a passkey device'}</button><button type="button" onClick={() => void checkDeviceApproval()} disabled={!!busy} className="w-full border border-slate-600 py-2 rounded-xl">Check device approval</button></div>}
        <button type="button" onClick={() => void forget()} disabled={!!busy} className="w-full border border-red-900/60 text-red-300 py-2 rounded-xl flex justify-center gap-2"><Trash2 className="w-4 h-4" />{busy === 'forget' ? 'Forgetting…' : navigator.onLine ? 'Forget this device' : 'Delete local device data'}</button>
        {!navigator.onLine && <p className="text-xs text-amber-300">Offline deletion removes this browser’s encrypted data. Reconnect later to revoke the server device record.</p>}
        <div className="border-t border-slate-700 pt-4"><h4 className="font-medium text-white">Personal recovery phrase</h4>{!phrase ? <button type="button" onClick={startRecovery} className="mt-2 text-primary-400">Create or replace recovery phrase</button> : <div className="mt-3 space-y-3"><p className="rounded-xl bg-slate-900 p-3 font-mono text-sm text-white">{phrase.join(' ')}</p><p className="text-xs text-slate-400">Write this down now. It is shown once and is never saved in this browser.</p>{positions.map((position, index) => <label key={position} className="block text-sm text-slate-300">Word {position + 1}<input value={answers[index]} onChange={event => setAnswers(current => current.map((answer, answerIndex) => answerIndex === index ? event.target.value.trim().toLowerCase() : answer))} className="mt-1 w-full rounded-lg bg-slate-900 border border-slate-700 p-2 text-white" /></label>)}<label className="flex gap-2 text-sm text-slate-300"><input type="checkbox" checked={replace} onChange={event => setReplace(event.target.checked)} />Replace an existing phrase</label><button type="button" disabled={busy === 'recovery'} onClick={() => void saveRecovery()} className="w-full bg-primary-600 py-2 rounded-xl">{busy === 'recovery' ? 'Saving…' : 'Confirm recovery phrase'}</button></div>}</div>
    </section>;
}
